server:
  port: 8084
  servlet:
    context-path: /payment-service

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: Pooja@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        max-page-size: 20
        default-page-size: 10
        one-indexed-parameter: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: localhost

jwt:
  secret: ajogjwoue023uojwlajAKJAEJO98uwpPLFMELJ2OKAsaefo283pMLVLE
  expiration: 86400000
  refresh-expiration: 604800000