spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:mysql://localhost:3306/moviedb?useSSL=false&serverTimezone=UTC
    username: root
    password: Pooja@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 20
        one-indexed-parameters: true
    redis:
      port: 6379
      host: localhost
      password:
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
      timeout: 2000ms
      connect-timeout: 2000ms
  cache:
    type: redis

server:
  port: 8081
  servlet:
    context-path: /api/v1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: ajogjwoue023uojwlajAKJAEJO98uwpPLFMELJ2OKAsaefo283pMLVLE
  expiration: 86400000
  refresh-expiration: 604800000